project:
  title: "masterThesis"
  type: website
  output-dir: docs
  
website: 
  title: "Thesis Results of Leander Kühne"
  favicon: favmonster.png
  bread-crumbs: true
  page-navigation: true
  navbar: 
    background: secondary
    search: true
    left: 
      - masterThesis.qmd
      - sidebar:MM
      - sidebar:plateReader
      - sidebar:mazeChips
    right: 
     - href: "https://github.com/lekuehne/masterThesis"
       text: "GitHub"
       icon: github
       
  sidebar:
    - id: plateReader
      title: "Well-Mixed"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Experiments"
          contents: plateReader/**/*.qmd

    - id: mazeChips
      title: "Spatially Structured"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Fractal Maze Chip Experiments"
          contents: mazeChips/**/*.qmd
        - section: "Analysis"
          contents: SysBioModelingClass.qmd
        
    - id: MM
      title: "Material & Methods"
      contents:
        - MM.qmd
        - NI enrichment and extraction.qmd
    
format: 
  html:
    theme: 
    - cosmo
    - brady
    css: styles.css
    toc: true