project:
  title: "masterThesis"
  type: website
  output-dir: docs
  
website: 
  title: "Master Thesis Results of Leander Kühne"
  #favicon: <.png>
  navbar: 
    background: secondary
    search: true
    left: 
      - masterThesis.qmd
      - MM.qmd
      - NI enrichment and extraction.qmd
      - sidebar:plateReader
      - sidebar:mazeChips
    right: 
     - href: "https://github.com/lekuehne/masterThesis"
       text: "GitHub"
       icon: github
       
  sidebar:
    - id: plateReader
      title: "Plate Reader"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - plateReader/001-all_conditions_same_OD/001-all_conditions_same_OD.qmd
        - plateReader/002-PP-BS-dil_series/002-PP-BS-dil_series.qmd
        - plateReader/004-BS_BSPP_dil_series/report.qmd
        
    - id: mazeChips
      title: "Fractal Maze Chips"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - mazeChips/experiment.qmd
      
    
format: 
  html:
    theme: 
    - cosmo
    - brady
    css: styles.css
    toc: true